Change property names
amanoese/blue-vue pull request #16
Opened 2016-11-10 12:26 UTC by ukenhk-kuni077

2016-11-11 10:45 UTC, amanoese requested changes
thank you for pull request.
but you need a little this code fix.

2016-11-11 10:45 UTC, amanoese commented on src/App.vue
> -        regDate:x.regDate.replace(/\//g,'-')
regDate format is different of html5 specification.
need to data convert on either db or js.
this code is need.

2016-11-14 03:06 UTC, ukenhk-kuni077 commented
こんにちは。
國藤です。

多嘉さん、
pull request の方のコメントに書かなかったかもしれませんが、日付は db 側の値を直しました。
( ハイフン区切りに修正した )

よろしくお願いします。

2016-11-11 19:45 GMT+09:00 amanoese <notifications@github.com>:

> *@amanoese* requested changes on this pull request.
>
> thank you for pull request.
> but you need a little this code fix.
> ------------------------------
>
> In src/App.vue
> <https://github.com/amanoese/blue-vue/pull/16#pullrequestreview-8176721>:
>
> > @@ -95,13 +95,11 @@ export default {
>      .then(response=>response.json())
>      .then(json=>{
>        console.log(JSON.stringify(json,null,'\t'));
> -      this.taskDatas = json.map(x=>Object.assign(x,{
> -        title : x.todoText,
> -        regDate:x.regDate.replace(/\//g,'-')
>
> regDate format is different of html5 specification.
> need to data convert on either db or js.
> this code is need.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/amanoese/blue-vue/pull/16#pullrequestreview-8176721>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AV6Iyp-jVsKFgX9u3NR3LUTw_apeB_yaks5q9EdagaJpZM4Kumop>
> .
>

2016-11-21 04:01 UTC, amanoese commented
Conflict happened occurred by this pull request.
Please merge my master branch into the pull request branch.

The cause is your master branch and my master branch are different.
Your branch is not merge my branch using fast-forward few days ago.

2016-11-21 11:51 UTC, ukenhk-kuni077 commented
コンフリクト解消しました。

2016-11-21 17:27 UTC, merged