92 branch
amanoese/blue-vue pull request #3
Opened 2016-10-21 11:18 UTC by ukenhk-kuni077

ADD category , location listbox to task detail.

2016-10-21 13:04 UTC, amanoese commented on src/Task.vue
> +          <option>other</option>
need attribute "value"

2016-10-21 13:04 UTC, amanoese commented on src/Task.vue
> +          <option>other</option>
need attribute "value"

2016-10-21 13:15 UTC, amanoese requested changes

2016-10-21 13:15 UTC, amanoese commented on src/Task.vue
> +        location : <select v-model.sync="task.location">
select tag need label tag.

matteriarize is restrict any html code .
[check for this page](http://materializecss.com/forms.html#select)

2016-10-22 02:06 UTC, ukenhk-kuni077 commented
I pushed new my code.
Please check it out.
Thanks.

2016-10-27 05:45 UTC, closed without merging