Recordのスペル修正
amanoese/blue-vue pull request #6
Opened 2016-10-22 10:54 UTC by ukenhk-kuni077

2016-10-22 10:58 UTC, amanoese requested changes

2016-10-22 10:58 UTC, amanoese commented on src/App.vue
> +          <h4>delete</h4>
is this need ?

2016-10-24 03:12 UTC, ukenhk-kuni077 commented
delete dupulicated "delete" text.

2016-10-25 15:14 UTC, merged

2016-10-25 15:16 UTC, amanoese commented
thanks!